name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Lint
      run: go vet -v ./...

    # TODO: Enable tests once we have a running redis db for integration testing
    # - name: Test
    #   run: go test -v ./...

    - name: Build
      run: go build -v ./...
